### ISSUE TITLE
Mark Complete

### ISSUE THREAD

**Issue by itsbuji** [akshidas/custom-erc20-token-todolist#2] opened 2024-06-12 17:30 UTC
A user should be able to mark their task as complete

### Constraints
1. Marking a task as complete will reward the user

##### The percentage is calculated by finding 
$c - currentTime$
$s = startTime$
$e = endTime$
$totalTime = e -s$
$elapsedTime = c - s$

$percentageOfTimeElapsed = (elapsedTime / totalTime) x 100$
and if the $percentageOfTimeElapsed$ is denoted $pe$ by  of time elapsed is:

- $pe$ <= 10% give the user 15 tokens
- 10% < $pe$ <= 20% give the user 14 tokens
- 20% < $pe$ <= 30% give the user 13 tokens
- 30% < $pe$ <= 40% give the user 12 tokens
- 40% < $pe$ < 50%  give the user 11 tokens
- $pe$ = 50% give the user 10 tokens
- 50% < $pe$ <= 60% give the user 9 tokens
- 60% < $pe$ <= 70% give the user 7 tokens
- 70% < $pe$ <= 80% give the user 5 tokens
- 80% < $pe$ <= 90% give the user 3 tokens
- 90% < $pe$ <= 100% give the user 1 tokens
- 100% < $pe$ give the user 0 tokens

**Comment by akshaykrm** [comment] 2024-06-20 15:30
The issue is transferred to on hold as it needs front end to do, limited by my knowledge of smart contracts

**Closed as completed** 2024-07-02 17:14 UTC
Labels: enhancement
